<!-- OPÇÃO DE SEGMENTOS A SEREM ESCOLHIDOS -->
<!-- NO MOMENTO TODOS CONTAM COMO 12%, A CONVERSÃO PADRÃO -->
<!-- MAS FUTURAMENTE ESPECIFICAR A % PARA CADA SEGMENTO -->
function calc_total(){
            var qtd = parseInt(document.getElementById('iQuantidade').value);
            var x = (document.getElementById('iSegmento').value);
            var total;
            if(x=='ONG'){
            	x=12/100;
            }
            if(x=='Varejo'){
            	x=12/100;
            }
            if(x=='AutS'){
            	x=12/100;
            }
            if(x=='AutP'){
            	x=12/100;
            }
            if(x=='AutA'){
            	x=12/100;
            }
            if(x=='EduS'){
            	x=12/100;
            }
            if(x=='EduP'){
            	x=12/100;
            }
            if(x=='EduA'){
            	x=12/100;
            }
            if(x=='EntS'){
            	x=12/100;
            }
            if(x=='EntP'){
            	x=12/100;
            }
            if(x=='EntA'){
            	x=12/100;
            }
            if(x=='FinS'){
            	x=12/100;
            }
            if(x=='FinP'){
            	x=12/100;
            }
            if(x=='FinA'){
            	x=12/100;
            }
            if(x=='SauS'){
            	x=12/100;
            }
            if(x=='SauP'){
            	x=12/100;
            }
            if(x=='SauA'){
            	x=12/100;
            }
            if(x=='RHS'){
            	x=12/100;
            }
            if(x=='RHP'){
            	x=12/100;
            }
            if(x=='RHA'){
            	x=12/100;
            }
            if(x=='TecS'){
            	x=12/100;
            }
            if(x=='TecP'){
            	x=12/100;
            }
            if(x=='TecA'){
            	x=12/100;
            }
            if(x=='MarS'){
            	x=12/100;
            }
            if(x=='MarP'){
            	x=12/100;
            }
            if(x=='MarA'){
            	x=12/100;
            }
            if(x=='MidS'){
            	x=12/100;
            }
            if(x=='MidP'){
            	x=12/100;
            }
            if(x=='MidA'){
            	x=12/100;
            }
            if(x=='ViaS'){
            	x=12/100;
            }
            if(x=='ViaP'){
            	x=12/100;
            }
            if(x=='ViaA'){
            	x=12/100;
            }
            if(x=='ImoS'){
            	x=12/100;
            }
            if(x=='ImoP'){
            	x=12/100;
            }
            if(x=='ImoA'){
            	x=12/100;
            }
            if(x=='ApiS'){
            	x=12/100;
            }
            if(x=='ApiP'){
            	x=12/100;
            }
            if(x=='ApiA'){
            	x=12/100;
            }
            total = (qtd*x);
            document.getElementById('iTotal').value = total;
        }